### ISSUE TITLE
The script does not work for firefox --new-window if firefox is already opened

### ISSUE THREAD

**Issue by guanghwang** [Synthetica9/sway-floating#1]
Thanks for this script. 

I tested it with `termite`, `pcmanfm-qt` and `firefox`. It works for `termite`, but not works for `pcmanfm-qt` and `firefox` if I try to open new instances of these two programs.

Here is my sway version
```
local/sway 1:1.2-5
```

Please let me know if you need more info. 

Thank you very much.

**Comment by Synthetica9** [comment]
Yeah, this script tries to detect all windows opened by the process that it spawns, but `firefox --new-window` just sends a signal to an already existing process. I'll keep this open, but I wouldn't know how to fix it.

**Comment by guanghwang** [comment]
Thanks for the explanation. I got an workaround
```
floating firefox --new-instance -p new_profile
```
